Countries: ["FR", "DE"]

Data_structure:
  GFS:  ["FREQ", "ADJUSTMENT", "REF_AREA", "COUNTERPART_AREA", 
         "REF_SECTOR", "COUNTERPART_SECTOR", "CONSOLIDATION",
         "ACCOUNTING_ENTRY", "STO", "INSTR_ASSET", "MATURITY", 
         "EXPENDITURE", "UNIT_MEASURE", "CURRENCY_DENOM",
         "VALUATION", "PRICES", "TRANSFORMATION", "CUST_BREAKDOWN"]
  
  MNA: ["FREQ", "ADJUSTMENT", "REF_AREA", "COUNTERPART_AREA", 
         "REF_SECTOR", "COUNTERPART_SECTOR","ACCOUNTING_ENTRY", 
         "STO", "INSTR_ASSET", "ACTIVITY", "EXPENDITURE", 
         "UNIT_MEASURE", "PRICES", "TRANSFORMATION"]
