Countries: ["EA19", "EA20", "DE", "FR", "IT", "ES", "NL", "BE", "AT", "FI", "PT", "EL", "IE", "SK", "LU", "SI", "LT", "LV", "EE", "CY", "MT", "HR"]

Data_structure:
  GFS:  ["FREQ", "ADJUSTMENT", "REF_AREA", "COUNTERPART_AREA", 
         "REF_SECTOR", "COUNTERPART_SECTOR", "CONSOLIDATION",
         "ACCOUNTING_ENTRY", "STO", "INSTR_ASSET", "MATURITY", 
         "EXPENDITURE", "UNIT_MEASURE", "CURRENCY_DENOM",
         "VALUATION", "PRICES", "TRANSFORMATION", "CUST_BREAKDOWN"]
  
  namq_10_gdp: ["FREQ", "unit", "s_adj", "na_item", "geo"]
