name: Run MNA data

on:
  schedule:
  # 25th january at 13:00
    - cron: '00 13 25 1 *' 
  # 25th april at 13:00
    - cron: '00 13 25 4 *' 
  # 25th july at 13:00
    - cron: '00 13 25 7 *' 
  # 25th october at 13:00
    - cron: '00 13 25 10 *' 
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout out repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN_CI }}

      - name: Configure Git
        run: |
          git config user.name Thomas Faria
          git config user.email 57811152+ThomasFaria@users.noreply.github.com
    
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.2'

      - name: Install libcurl4
        run:  sudo apt install libcurl4-openssl-dev
        
      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Update MNA data
        run: |
          targets::tar_make()
        shell: Rscript {0} 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
          TAR_PROJECT: "MNA"
